config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'

  resources :lists do |member|
    resources :expenses, only: %i[show new create edit update destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expectation.rb
# == Schema Information
#
# Table name: expectations
#
#  id         :bigint(8)        not null, primary key
#  list_id    :bigint(8)
#  month_id   :bigint(8)
#  amount     :decimal(, )
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Expectation < ApplicationRecord
  belongs_to :list
  belongs_to :month

  validates :list, uniqueness: { scope: :month }
end

app/models/expense.rb
# == Schema Information
#
# Table name: expenses
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  amount     :decimal(, )
#  list_id    :bigint(8)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  month_id   :bigint(8)
#

class Expense < ApplicationRecord
  belongs_to :list
  belongs_to :month
end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id          :bigint(8)        not null, primary key
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  dirrection  :boolean          default(FALSE)
#  reoccurring :boolean          default(FALSE)
#

class List < ApplicationRecord
  has_many :expenses
  has_many :expectations
end

app/models/month.rb
# == Schema Information
#
# Table name: months
#
#  id         :bigint(8)        not null, primary key
#  month      :integer          not null
#  year       :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Month < ApplicationRecord
  has_many :expectations, dependent: :destroy
  has_many :expenses, dependent: :nullify

  after_create :add_expectations

  validates :month, uniqueness: { scope: :year }

  def name
    "#{month+1} - #{year}"
  end

  def add_expectations
    return unless Month.count > 1
    new_expectations = Month.order(id: :desc).offset(1).first.expectations.map do |exp|
      Expectation.create!(list_id: exp.list_id, amount: exp.amount, month: self)
      # if exp.list.reoccurring
      #   exp.list.expenses.each do ||
      # end
    end
    self.update(expectations: new_expectations)
  end

  def self.current
    curr_date = Time.zone.now
    self.find_or_create_by(month: curr_date.month - 1, year: curr_date.year)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_list
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # def index
  #   @expenses = @list.expenses
  # end

  def show
  end

  def new
    @expense = Expense.new(month_id: params[:month_id])
  end

  def edit
  end

  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to list_url(@list), notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: list_url(@list) }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to list_url(@list), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: list_url(@list) }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to list_url(@list), notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_expense
      @expense = @list.expenses.find(params[:id])
    end

    def set_list
      @list = List.find(params[:list_id])
    end
    
    def expense_params
      tmp_params = params.require(:expense).permit(:name, :amount, :month_id)
      tmp_params[:list_id] = @list.id
      tmp_params
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :set_month, only: [:index, :show]

  def index
    @sums = List.includes(expenses: [:month])
                .group('list_id')
    @sums = @sums.where('expenses.month_id = ?', @month.id) unless @all == true
    @sums = @sums.sum('expenses.amount')
    @out = List.order(created_at: :asc)
               .where(dirrection: false)
               .left_outer_joins(:expectations)

    @in = List.order(created_at: :asc)
              .where(dirrection: true)
              .left_outer_joins(:expectations)

    unless @all == true
      @out = @out.where('expectations.month_id = ? OR expectations.month_id IS NULL', @month.id)
      @in = @in.where('expectations.month_id = ? OR expectations.month_id IS NULL', @month.id)
    else
      @out = @out.distinct
      @in = @in.distinct
    end
  end

  def show
    @expenses = @list.expenses
    @expenses = @expenses.where('expenses.month_id = ?', @month.id) unless @all
    @sum = @expenses.sum(:amount)
  end

  def new
    @list = List.new
  end

  def edit
  end

  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_url, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to lists_url, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_list
      @list = List.find(params[:id])
    end

    def set_month
      @all = false
      @month = if params[:month_id].present?
                 if params[:month_id].to_i == -1
                   @all = true
                   Month.current
                 else
                   Month.find(params[:month_id])
                 end
               elsif params[:month].blank? || params[:year].blank?
                 Month.current
               else
                 Month.find_or_create_by(month: params[:month], year: params[:year])
               end
    end

    def list_params
      params.require(:list).permit(:name, :dirrection)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/expenses/_form.html.slim
= f.alert_message t('form.alert_message')
= f.text_field :name, required: true
= f.number_field :amount, required: true, step: :any
= f.collection_select(:month_id, Month.all, :id, :name)

= f.submit 'Submit', class: 'btn btn-primary float-right'

app/views/expenses/edit.html.slim
.wrapper
  .container.mt-2
    .row.justify-content-center
      .col-md-10
        h3 = 'Edit expense'
        = bootstrap_form_for(@expense, url: list_expense_path(@list, @expense)) do |f|
          = render 'form', f: f

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expenses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th>List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.name %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.list_id %></td>
        <td><%= link_to 'Show', list_expense_path(@list, expense) %></td>
        <td><%= link_to 'Edit', edit_list_expense_path(@list, expense) %></td>
        <td><%= link_to 'Destroy', list_expense_path(@list, expense), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_list_expense_path(@list) %>

app/views/expenses/new.html.slim
.wrapper
  .container.mt-2
    .row.justify-content-center
      .col-md-10
        h3 = 'New expense'
        = bootstrap_form_for(@expense, url: list_expenses_path(@list)) do |f|
          = render 'form', f: f

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @expense.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>List:</strong>
  <%= @list.name %>
</p>

<%= link_to 'Edit', edit_list_expense_path(@list, @expense) %> |
<%= link_to 'Back', list_path(@list) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    in?
    <%= form.check_box :dirrection %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/_lists.html.slim
table.table
  thead
    tr
      th Name
      th Amount
      th Expected
      th Ops
  tbody
    - lists.each do |list|
      tr
        td = link_to "#{list.name}#{list.reoccurring ? '*' : ''}", list_path(list, month_id: @month_id)
        td = @sums[list.id] || 0
        td = list&.expectations&.find_by(month_id: @month.id)&.amount || 0
        td
          .float-right.rowww
            = link_to '', new_list_expense_path(list, month_id: @month.id), class: 'btn btn-success btn-sm m-1'
            = link_to '', edit_list_path(list), class: 'btn btn-info btn-sm m-1'
            = link_to '', list, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm m-1 '','

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.slim
.wrapper
  .container.mt-2
    .row.justify-content-center
      .col-md-10
        p id="notice"
          = notice

        = link_to 'New List', new_list_path, class: 'btn btn-success float-right'
        h1 Lists
        br
        br

        = link_to 'Today', lists_path(month_id: Month.current.id)
        = "   "
        = link_to 'All', lists_path(month_id: -1)
        br
        - if @all
          = 'No date, all'
        - else
          = link_to 'Prev', lists_path(month: @month.month == 0 ? 11 : @month.month - 1, year: @month.month == 0 ? @month.year - 1 : @month.year)
          = "  #{@month.name}  "
          = link_to 'Next', lists_path(month: @month.month == 11 ? 0 : @month.month + 1, year: @month.month == 11 ? @month.year + 1 : @month.year)

        .row
          .col-md-6
            .card.m-2
              .card-body
                h2.card-title Out
                = render 'lists', lists: @out
          .col-md-6
            .card.m-2
              .card-body
                h2.card-title In
                = render 'lists', lists: @in

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.slim
.wrapper
  .container.mt-2
    .row.justify-content-center
      .col-md-10
        p#notice = notice

        h1
          strong = "Name: #{@list.name}"

        = link_to 'Add', new_list_expense_path(@list), class: 'btn btn-success float-right'
        h2 = @sum

        = link_to 'Today', list_path(@list, month_id: Month.current.id)
        = "   "
        = link_to 'All', list_path(@list, month_id: -1)
        br
        - if @all
          = 'No date, all'
        - else
          = link_to 'Prev', list_path(@list, month: @month.month == 0 ? 11 : @month.month - 1, year: @month.month == 0 ? @month.year - 1 : @month.year)
          = "  #{@month.name}  "
          = link_to 'Next', list_path(@list, month: @month.month == 11 ? 0 : @month.month + 1, year: @month.month == 11 ? @month.year + 1 : @month.year)

        table.table
          - @expenses.each do |expense|
            tr
              td = expense.id
              td = link_to expense.name, list_expense_path(@list, expense)
              td = expense.amount
              td
                = link_to 'Edit', edit_list_expense_path(@list, expense), class: 'btn btn-info m-2'
                = link_to 'Destroy', list_expense_path(@list, expense), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger m-2'

        br
        = link_to 'Edit', edit_list_path(@list)
        = link_to 'Back', lists_path